name: Build Android Projeto GTA holysa

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # Removi o cache inicial para evitar conflito se o download anterior corrompeu
          
      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      # Corrigi a versão do NDK para bater com o que você quer usar (26 estável)
      - name: Instalar NDK e CMake
        run: |
          sdkmanager "ndk;26.1.10909125" "cmake;3.22.1"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      # Adicionei um passo de "Warmup" para garantir que o gradle baixe antes da build pesada
      - name: Baixar Dependências
        run: ./gradlew help

      - name: Compilar APK (Debug)
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Upando o APK
        uses: actions/upload-artifact@v4
        with:
          name: gta-mobile-build
          path: app/build/outputs/apk/debug/*.apk
